# Merge script for replication project
# DVAD14 Karlstads Universitet
# Noah Bühlmann
#
# PowerShell 7 or higher is required to run this script!

### Begin of Settings ###
$projectPath = $PSScriptRoot
# Folder that contains all the subfolders with the data per commit generated by buildScript-jabref.ps1
$metricsPath = Join-Path $projectPath "commits"
# Name of the folder that will contain the merged data (it will be created, if it doesn't exists)
$outputFolder = Join-Path $projectPath "data\jabref"
# Array of metric files, that should be merged
$metricFiles = @("PM.csv","CM.csv","HL.csv","UD.csv","classCL.csv","packageCL.csv")
### End of Settings ###

if (Test-Path -Path $outputFolder) {
    Write-Host "Output folder exists!" -ForegroundColor Green
} else {
    Write-Error "Output folder doesn't exist yet. Please create: $outputFolder"
    exit
}

Set-Location $metricsPath

foreach ($metric in $metricFiles) {
    Write-Host "Merging $metric" -ForegroundColor Yellow
    @(Get-ChildItem -Recurse -File -Filter "$metric").fullname | Import-Csv | Export-Csv (Join-Path $outputFolder "$metric") -NoTypeInformation -UseQuotes AsNeeded
}

Write-Host "Merging complete" -ForegroundColor Green
