# Merge script for replication project
# DVAD14 Karlstads Universitet
# Noah Bühlmann
#
# PowerShell 7 or higher is required to run this script!

### Begin of Settings ###
# Folder that contains all the subfolders with the data per commit generated by buildScript-jabref.ps1
$metricsPath = "C:\Users\noahb\Desktop\test"
# Name of the folder that will contain the merged data (it will be created, if it doesn't exists)
$outputFolder = "MERGED"
# Array of metric files, that should be merged
$metricFiles = @("CM.csv","HL.csv","UD.csv","classCL.csv","packageCL.csv")
### End of Settings ###

Set-Location $metricsPath

if (Test-Path -Path (Join-Path $metricsPath $outputFolder)) {
    Write-Host "Output folder exists!" -ForegroundColor Green
} else {
    Write-Host "Output folder doesn't exist. Creating it." -ForegroundColor Yellow
    New-Item -Path $metricsPath -Name $outputFolder -ItemType "directory" | Out-Null
}

foreach ($metric in $metricFiles) {
    Write-Host "Merging $metric" -ForegroundColor Yellow
    @(Get-ChildItem -Recurse -File -Filter "$metric").fullname | Import-Csv | Export-Csv ".\MERGED\$metric" -NoTypeInformation -UseQuotes AsNeeded
}

Write-Host "Merging complete" -ForegroundColor Green